### ISSUE TITLE
Put up API docs online

### ISSUE THREAD

**Issue by zeenix** [GENIVI/rvi_lib#23]
All successful open-source public APIs put their docs online (and update them for each release) and it would be pretty great if this library follows that practice.

**Comment by tjamison** [comment]
@zeenix, do you mean something other than [the project's site pages](http://genivi.github.io/rvi_lib/)?

**Comment by zeenix** [comment]
No i meant API docs like but I actually just realized that you already have them under the "Files" link on the top:

http://genivi.github.io/rvi_lib/files.html

I'd suggest adding a link to them on the Main page, maybe the only link under "Documentation" section should take you there instead of the "Main page" itself?

**Comment by gunnarx** [comment]
Looks like this is resolved right?  We have a little side discussion ongoing on what docs and pointers we should have from GENIVI Wiki to the project, and which bug tracker is preferred by GENIVI and preferred by the maintainer, but in terms of actual feedback on the code base itself, I'd propose this is resolved, do you agree?

**Comment by tjamison** [comment]
I'll be updating the link in the README to go directly to the files page per @zeenix's suggestion and likely updating a few other things pending the outcome of the side discussion. @zeenix, are you satisfied that this issue is resolved?

**Comment by zeenix** [comment]
Sorry for the late reply but this issue itself is not yet resolved until there is a link under "Documentation" on the main page points to http://genivi.github.io/rvi_lib/files.html .

**Comment by tjamison** [comment]
#30 resolves this issue

**Comment by zeenix** [comment]
@tjamison There must be some misunderstanding cause this is not resolved yet and can't be solved by source code changes. As I said in my last comment:

> Sorry for the late reply but this issue itself is not yet resolved until there is a link under "Documentation" on the main page points to http://genivi.github.io/rvi_lib/files.html .

That's still not the case.

**Comment by tjamison** [comment]
@zeenix Yes, I agree that there is a misunderstanding. The "GitHub Pages" link (under the "Documentation" header) now points to http://genivi.github.io/rvi_lib/files.html per commit https://github.com/GENIVI/rvi_lib/commit/e6547bc528fa2cfaa1953fcec2e4a5687139a895. If this does not resolve your comment, could you please clarify?

**Comment by zeenix** [comment]
@tjamison Sure. You are talking of http://genivi.github.io/rvi_lib/files.html

where as I'm talking about the main page: http://genivi.github.io/rvi_lib/index.html

Under the Documentation heading, the only link links you back to the main page, i-e it doesn't load anything.

**Comment by tjamison** [comment]
I see. I've pushed a new commit refreshing the Doxygen docs. Does this resolve the issue for you?

**Comment by zeenix** [comment]
@tjamison Yay, it works now! :)
